<?php

/*
  Falcon Framework :: public/index.php
  -
  This file initializes your app. DO NOT EDIT THIS FILE as it simply loads your
  app, what is actually displayed is the view in app/views that is given by the
  controller.
*/

  require_once('../app/init.php');

  $app = new App;
